sudo: required
dist: xenial
services:
  - xvfb
language: python
python: 3.8
addons:
  chrome: stable

install:
  - pip install -r requirements.txt
addons:
  chrome: stable
before_script:
before_install:
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:/home/travis/build/zhaoming0/amz
script: 
  python checkIndex.py
