language: python
python:
  - "3.8"
sudo: "required"

install:
  - pip install -r requirements.txt
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - ls
  - ls * -l
  - pwd
  - export PATH=$PATH:/home/travis/build/zhaoming0/amz

    
script:
  chromedriver 
  python chrome.py
