language: python
python:
  - "3.8"
sudo: "required"

install:
  - pip install -r requirements.txt
addons:
  chrome: stable
before_script:
before_install:
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - ls
  - ls * -l
  - pwd
  - export PATH=$PATH:/home/travis/build/zhaoming0/amz

    
script: 
  python chrome.py
