version: 2
jobs:
  build:
    docker:
      -image: circleci/python:3.8-browsers
  step:
      - checkout
      - run:
          name: download selenium
          command: curl -O https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip | unzip chromedriver_linux64.zip

  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python chrome.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
