version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    step:
      - checkout
      - run: pip3 --version
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
          
