version: 2.1

jobs:
  build:
    docker:
      -image: circleci/python:3.6.2-stretch-browsers
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python chrome.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
